name: Build Aseprite

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different
  pull_request:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.21.2'  # Specify the version you need

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.bat
          ./vcpkg integrate install

      - name: Install dependencies
        run: |
          cd vcpkg
          ./vcpkg install skia lua libpng zlib

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build Aseprite
        run: |
          cd build
          cmake --build . --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: aseprite
          path: build/bin/Release/Aseprite.exe  # Adjust the path if necessary
